# Generated by Django 5.0.2 on 2024-02-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('passenger_count', models.IntegerField()),
            ],
        ),
    ]
