# Generated by Django 4.2.5 on 2024-02-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
