# Generated by Django 5.0.2 on 2024-02-29 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0003_airline_plane_delete_flight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_country', models.CharField(max_length=100)),
                ('destination_country', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passenger_count', models.IntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbp.airline')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbp.plane')),
            ],
        ),
    ]
