# Generated by Django 4.2.5 on 2024-02-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0004_bookroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookroom',
            old_name='Traveler',
            new_name='traveler',
        ),
    ]
