# Generated by Django 4.2.5 on 2024-02-29 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0005_rename_traveler_bookroom_traveler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookroom',
            name='rooms',
        ),
        migrations.AddField(
            model_name='bookroom',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tbp.room'),
        ),
    ]
