# Generated by Django 5.0.2 on 2024-02-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0006_seatbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbooking',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbp.seat'),
        ),
    ]
