# Generated by Django 5.0.2 on 2024-02-29 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0007_alter_seatbooking_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_country', models.CharField(max_length=100)),
                ('arrival_country', models.CharField(max_length=100)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbp.seat')),
                ('seat_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tbp.seatbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
