# Generated by Django 4.2.5 on 2024-02-29 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0007_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='checkout_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookroom',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
