# Generated by Django 5.0.2 on 2024-02-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0008_flightbooked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightBooked',
        ),
    ]
