# Generated by Django 4.2.5 on 2024-02-29 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0009_alter_bookroom_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Van', 'Van'), ('Hatchback', 'Hatchback'), ('Convertible', 'Convertible'), ('Coupe', 'Coupe')], max_length=100)),
                ('license_no', models.CharField(max_length=50)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbp.agency')),
            ],
        ),
    ]
