# Generated by Django 4.2.5 on 2024-02-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0012_remove_bookvehicle_travelers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
