# Generated by Django 4.2.5 on 2024-03-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0014_airline_plane_seat_seatbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='arrival_country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
        migrations.AddField(
            model_name='plane',
            name='departure_country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
